services:
  neo4j:
    image: neo4j:5.12
    container_name: movie_graph_db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/TSCD2025
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - ./neo4j_data:/data
  
  
  localstack:
    image: localstack/localstack:latest
    container_name: movie_aws_sim
    ports:
      - "4566:4566"            # Puerto principal para SQS
    environment:
      - SERVICES=sqs,s3           # Solo activamos SQS para ahorrar memoria
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack_data:/var/lib/localstack" # Persistencia (opcional)